on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
      
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: true

      - name: Restore Api Dependencies
        run: dotnet restore Api/Api.csproj

      - name: Build
        run: dotnet build --configuration Release Api/Api.csproj
      
      - name: Install Compatible EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 6.0.0


      - name: Migration
        run: |
          cd Api
          dotnet ef migrations add initialmigration
          dotnet ef database update

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/result Api/Api.csproj

      - name: Run Api
        run: |
          cd Api
          dotnet run --urls=http://localhost:7008
          cd ..

      - name: Run ApiWebClient
        run: |
          cd ApiWebClient
          dotnet run --urls=http://localhost:7093
          cd ..

      - name: Run Tests
        run: dotnet test
        continue-on-error: true
