on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
      
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: true

      - name: Restore Api Dependencies
        run: dotnet restore Api/Api.csproj

      - name: Build
        run: dotnet build --configuration Release Api/Api.csproj

      - name: Restore MVC Dependencies
        run: dotnet restore ApiWebClient/ApiWebClient.csproj

      - name: Build
        run: dotnet build --configuration Release ApiWebClient/ApiWebClient.csproj

      - name: Restore Test Dependencies
        run: dotnet restore Selenium/Selenium.csproj

      - name: Build
        run: dotnet build --configuration Release Selenium/Selenium.csproj
      
      - name: Install Compatible EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 6.0.0

      - name: Migration
        run: |
          cd Api
          dotnet ef migrations add initialmigration
          dotnet ef database update

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/result Api/Api.csproj

      - name: Run Apps
        run: |
          cd Api
          cmd /c "start dotnet run --urls=http://localhost:5071"
          cd ../ApiWebClient
          cmd /c "start dotnet run --urls=http://localhost:5117"
          cd ../Selenium
          dotnet test
          exit 1
